---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: print-nanny-blog-ghost
  annotations:
    #networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
    kubernetes.io/ingress.global-static-ip-name: "ghost-static-ip"
    networking.gke.io/managed-certificates: blog-dot-print-nanny-dot-com
spec:
  backend:
    serviceName: print-nanny-blog-ghost
    servicePort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: blog-dot-print-nanny-dot-com
spec:
  domains:
    - blog.print-nanny.com