apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  name: print-nanny-help
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-nanny-help
  serviceName: print-nanny-help
  template:
    metadata:
      labels:
        app: print-nanny-help
    spec:
      serviceAccountName: sql-webapp
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=print-nanny:us-central1:print-nanny-blog=tcp:3306"
        securityContext:
          runAsNonRoot: true
        ports:
          - containerPort: 3306
      - image: ghost:alpine
        name: ghost
        env:
        - name: url
          value: "http://help.print-nanny.com"
        - name: admin__url
          value: "https://help.print-nanny.com"
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Mailgun
        - name: mail__options__auth__user
          valueFrom:
            secretKeyRef:
              name: mailgun-smtp-auth
              key: user
        - name: mail__options__auth__pass
          valueFrom:
            secretKeyRef:
              name:  mailgun-smtp-auth
              key: password
        - name: mail__options__port
          value: "2525"
        - name: database__connection__host
          value: "127.0.0.1"
        - name: database__connection__user
          value: ghost
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name:  mysql-creds
              key: password
        - name: database__connection__database
          value: print_nanny_help
        ports:
        - containerPort: 2368
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: print-nanny-help-data
        livenessProbe:
          httpGet:
            path: /
            port: 2368
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 4
        readinessProbe:
          httpGet:
            path: /
            port: 2368
            httpHeaders:
              - name: X-Forwarded-Proto
                value: https
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 6
  volumeClaimTemplates:
  - metadata:
      name: print-nanny-help-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: print-nanny-help
spec:
  customRequestHeaders:
    headers:
    - "X-Forwarded-Proto:https"
---
apiVersion: v1
kind: Service
metadata:
  name: print-nanny-help
  labels:
    app: print-nanny-help
  annotations:
    cloud.google.com/backend-config: '{"default": "print-nanny-help"}'
spec:
  selector:
    app: print-nanny-help
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: print-nanny-help
spec:
  domains:
    - help.print-nanny.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: print-nanny-help
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
    kubernetes.io/ingress.global-static-ip-name: ghost-help-static-up
    networking.gke.io/managed-certificates: print-nanny-help
spec:
  backend:
    serviceName: print-nanny-help
    servicePort: 80
