---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  serviceName: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      serviceAccountName: sql-webapp
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=print-nanny:us-central1:print-nanny=tcp:5432"
        securityContext:
          runAsNonRoot: true
        ports:
          - containerPort: 5432
      - image: metabase/metabase
        name: metabase
        envFrom:
          - configMapRef:
              name: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    app: metabase
  annotations:
    cloud.google.com/backend-config: '{"default": "metabase"}'
spec:
  selector:
    app: metabase
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: metabase
spec:
  domains:
    - blog.print-nanny.com
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metabase
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
    kubernetes.io/ingress.global-static-ip-name: ghost-static-ip
    networking.gke.io/managed-certificates: metabase
spec:
  backend:
    serviceName: metabase
    servicePort: 80
