on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'INFO'
      plugin_version:
        description: 'Commitish or branch of the OctoPrint Nanny plugin to install in sandbox'
        default: 'devel'
        required: true
      octoprint_version:
        description: 'OctoPrint version to install in sandbox'
        default: '1.6.0rc3'
      fixtures:
        description: 'Load default fixture data?'
        default: true
        required: true
      user:
        description: 'Valid users are leigh, dzervas, polidoros'
        required: true
env:
  PRINT_NANNY_URL: ${{ github.events.inputs.user }}.sandbox.print-nanny.com
  OCTOPRINT_URL: ${{ github.events.inputs.user }}.sandbox.print-nanny.com/octoprint
  DJANGO_SUPERUSER_PASSWORD: ${{ secrets.SANDBOX_DJANGO_SUPERUSER_PASSWORD }}
  DJANGO_SUPERUSER_EMAIL: ${{ github.event.inputs.user }}@print-nanny.com
  DJANGO_SECRET_KEY: ${{ secrets.SANDBOX_DJANGO_SECRET_KEY }}
  STRIPE_PUBLIC_KEY: ${{ secrets.SANDBOX_STRIPE_PUBLIC_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.SANDBOX_STRIPE_SECRET_KEY }}
  MAILGUN_API_KEY: ${{ secrets.SANDBOX_MAILGUN_API_KEY }}
  MAILGUN_DOMAIN: ${{ secrets.SANDBOX_MAILGUN_DOMAIN }}
  DISCORD_TOKEN: ${{ secrets.SANDBOX_DISCORD_TOKEN }}
  HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }}
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.SANDBOX_GCP_SERVICE_ACCOUNT_KEY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.SANDBOX_GCP_SERVICE_ACCOUNT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Input Settings
      run: |
        echo "User: ${{ github.event.inputs.user }}" 
        echo "Branch: ${{ github.event.inputs.branch }}"
        echo "Loglevel: ${{ github.event.inputs.loglevel }}"
        echo "Plugin Version: ${{ github.event.inputs.plugin_version }}"
        echo "Octoprint Version: ${{ github.event.inputs.octoprint_version }}"
        echo "Load fixture data: ${{ github.event.inputs.fixtures }}"
    - name: Checkout branch
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Write deploy key
      run: echo $GCP_SERVICE_ACCOUNT_KEY > key.json
    - name: Active Service Account
      run: gcloud auth activate-service-account $GCP_SERVICE_ACCOUNT --key-file=key.json
    - name: Configure docker registry credentials
      run: gcloud auth configure-docker
    - name: Deploy sandbox instance
      run: make sandbox-deploy PROJECT="print-nanny-sandbox" DEPLOY_USER="${{ github.event.inputs.user }}" PRINT_NANNY_URL=$PRINT_NANNY_URL OCTOPRINT_URL=$OCTOPRINT_URL
    - name: Run cypress tests
      run: make cypress-local-run